config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cards
  resources :vendors
  resources :categories
  
  root 'card_charges#home'

  resources :card_charges do
    collection do
      get 'assign_categories'
      get 'process_bbva_credit'
      get 'process_bbva_debit'
      get 'process_amex_credit'
    end
  end

  get 'categorize_charges', to: 'card_charges#categorize_charges'
  get 'monthly_report', to: 'card_charges#monthly_report', as: 'monthly_report_card_charges'
  get 'charges_by_month', to: 'card_charges#charges_by_month', as: 'charges_by_month_card_charges'

end

app/models/card_charge.rb
class CardCharge < ApplicationRecord
    validates :card, presence: true

    belongs_to :category, optional: true
    belongs_to :card
    belongs_to :user 

    scope :positive_amounts, -> { where("amount > 0") }
end

app/controllers/card_charges_controller.rb
class CardChargesController < ApplicationController
    before_action :authenticate_user! 

    def index
      selected_card_id = params[:card_id]
      @card_charges = current_user.card_charges.order(date: :asc)

      #@cr_total = @card_charges.where(type_of_charge: "Cargo regular").sum(:amount)
      #@msi_total = @card_charges.where(type_of_charge: "Cargo MSI").sum(:amount)
      #@d_total = @card_charges.where(type_of_charge: "Depósito").sum(:amount)
    end
  
    def new
      @card_charge = CardCharge.new
    end

    def create 
      uploaded_file = params[:file]
      card_type = params[:card_type]

      case card_type
        when '1'
          process_bbva_credit(uploaded_file, card_type)
        when '2'
          process_bbva_debit(uploaded_file, card_type)
        when '3'
          process_amex_credit(uploaded_file, card_type)
        else
          redirect_to card_charges_path, alert: 'Tipo de tarjeta no válido.'
          return
      end

      redirect_to card_charges_path, notice: 'Los cargos fueron importados correctamente.'
    end

    def update
      @card_charge = CardCharge.find(params[:id])
      CardCharge.transaction do
        if @card_charge.update(card_charge_params)
          redirect_to assign_categories_card_charges_path, notice: 'Category assigned successfully.'
        else
          render :assign_categories
        end
      end
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Charge not found or already categorized."
      redirect_to assign_categories_card_charges_path(month: params[:month])
    end

    def process_bbva_credit(uploaded_file, card_type)
      pattern = /\A\d+ DE \d+ .+\z/
      xlsx = Roo::Spreadsheet.open(uploaded_file.path)
      header_rows_to_skip = 0
      xlsx.each_row_streaming(offset: header_rows_to_skip) do |row| 
        type_of_charge = "Cargo regular"
        data_str = row[0].value
        date = Date.strptime(data_str, '%d/%m/%Y') rescue nil
        
        if date
          description = row[1].value 
          if description =~ pattern
            type_of_charge = "Cargo MSI"
          end
    
          charge = row[2].value.to_f
          deposit = row[3].value.to_f
    
          amount = charge != 0 && !charge.nil? ? charge : deposit
          type_of_charge = "Depósito" if amount == deposit
    
          card_charge = CardCharge.new(
            date: date, 
            description: description, 
            amount: amount,
            card_id: card_type,
            user: current_user
          )
    
          if card_charge.save
            puts "CardCharge created successfully!"
          else
            Rails.logger.error "Charge creation failed: #{card_charge.errors.full_messages.join(', ')}"
          end
        else
          Rails.logger.error "Error en fecha: #{data_str}" 
        end
      end
    end
    
    def process_bbva_debit(uploaded_file, card_type)
      # Implement the logic for processing Card B here
      # Similar to process_card_a, but tailored for Card B's specific format
    end

    def process_amex_credit(uploaded_file, card_type)
      pattern = /\A\d+ DE \d+ .+\z/
      xlsx = Roo::Spreadsheet.open(uploaded_file.path)
      header_rows_to_skip = 7
      xlsx.each_row_streaming(offset: header_rows_to_skip) do |row| 
        type_of_charge = "Cargo regular"
        date_str = row[0].value
        puts "Fecha en string: #{date_str}"
        date = Date.strptime(date_str, '%d %b %Y') rescue nil
        
        description = row[2].value 
        if description =~ pattern
          type_of_charge = "Cargo MSI"
        end

        amount = row[5].value.to_f
        type_of_charge = "Depósito" if amount < 0

        if date
          charge = CardCharge.create(
            date: date, 
            description: description, 
            amount: amount, 
            type_of_charge: type_of_charge, 
            card_id: card_type,
            user: current_user
          ) 
          unless charge.valid?
            Rails.logger.error "Charge creation failed: #{charge.errors.full_messages.join(', ')}"
          end
        else
          Rails.logger.error "Error en fecha"
        end
      end
    end

    def assign_categories
      @selected_category_id = params[:category_id]
      @card_charges = current_user.card_charges

      if @selected_category_id.present? && @selected_category_id != ""
        @card_charges = @card_charges.where(category_id: @selected_category_id)
      else
        @card_charges = @card_charges.where(category_id: nil)
      end

      @total_uncategorized_count = CardCharge.where(category_id: nil).count
      @selected_category = Category.find_by(id: @selected_category_id) if @selected_category_id.present?
    end

    def categorize_charges
      uncategorized_charges = current_user.card_charges.where(category_id: nil)
      vendors = Vendor.all
    
      uncategorized_charges.each do |charge|
        vendors.each do |vendor|
          if vendor.name.downcase.in? charge.description.downcase
            charge.update(category_id: vendor.category_id) 
            break 
          end
        end
      end
      redirect_to root_path, notice: 'Uncategorized charges processed.' 
    end

    def monthly_report
      @card_charges = current_user.card_charges.positive_amounts
      start_date = params[:start_date]
      end_date = params[:end_date]
      selected_category_id = params[:category_id]
      selected_card_id = params[:card_id]
    
      @card_charges = @card_charges.where(date: start_date..end_date) if start_date.present? && end_date.present?
      @card_charges = @card_charges.where(category_id: selected_category_id) if selected_category_id.present?
      @card_charges = @card_charges.where(card_id: selected_card_id) if selected_card_id.present? # Use @card_charges here
    
      @category_totals = @card_charges.joins('LEFT OUTER JOIN categories ON categories.id = card_charges.category_id')
                                      .group("categories.name")
                                      .sum(:amount)
    
      uncategorized_total = @card_charges.where(category_id: nil).sum(:amount)
      @category_totals["Sin categoría"] = uncategorized_total if uncategorized_total > 0
    
      @account_totals = @card_charges.group(:card_id)
                                      .pluck(:card_id, Arel.sql('SUM(amount) as total_amount'), Arel.sql('COUNT(*) as transaction_count'))
    
      @card_charges = @card_charges.order(date: :asc)
    end    
    
    def charges_by_month
      @start_date = params[:start_date].present? ? Date.parse(params[:start_date]) : Date.today.beginning_of_year
      @end_date = params[:end_date].present? ? Date.parse(params[:end_date]) : Date.today.end_of_year
    
      @card_charges = current_user.card_charges.includes(:category).where(date: @start_date..@end_date).where('amount > 0') 

      @categories = @card_charges.map(&:category).uniq
      @charges_by_category_and_month = @card_charges.group_by(&:category)
                                                .transform_values { |charges| charges.group_by { |charge| charge.date.beginning_of_month }.transform_values { |charges| charges.sum(&:amount) } }
                                                .transform_values { |months| months.sort_by { |month, _| month }.to_h } 
    end

    private

    def card_charge_params
      params.require(:card_charge).permit(:category_id) 
    end
end

app/helpers/cardcharge_helper.rb
module CardchargeHelper
end

app/views/card_charges/assign_categories.html.erb
<div class="container mt-5">
    <h1 class="text-center mb-4">Asignar categorias</h1>

    <div class="text-center mt-4">
      <%= link_to "Página principal", root_path, class: "btn btn-primary" %> 
      <%= link_to "Categorias", categories_path, class: "btn btn-primary", target: "_blank" %> 
      <%= link_to "Proveedores", vendors_path, class: "btn btn-primary", target: "_blank" %> 
    </div>
    <br> <hr>

    <div class="row justify-content-center">
      <div class="col-md-6">
        <%= form_with url: assign_categories_card_charges_path, method: :get do |f| %>
          <div class="form-group">
            <%= f.label :category_id, "Seleciona la categoría:" %>
            <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name, params[:category_id]), { include_blank: "Todas las categorías" }, class: "form-control" %>
          </div>
          <br>
          <%= f.submit "Filtrar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  
    <br>
  
    <% if @card_charges.any? %>
      <div class="text-center mt-3">
        <h2>Cargos de la categoría <%= @selected_category&.name || "Todas" %></h2> 
        <p>Total de cargos: <%= @card_charges.count %></p>
      </div>
  
      <% @card_charges.each do |charge| %>
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="card mb-3">
              <div class="card-body">
                <p>Fecha: <%= charge.date.strftime("%d/%m/%Y") %></p>
                <%= charge.description %> - $<%= charge.amount %>
                <div class="mb-3">
                  <%= form_with(model: charge, url: card_charge_path(charge), method: :patch) do |f| %>
                    <br>
                    <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name, charge.category_id), { include_blank: "Sin categoría" }, class: "form-control" %> 
                    <%= f.submit "Reclasificar", class: "btn btn-secondary" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="mt-6 text-center">Sin cargos por reclasificar</p> 
    <% end %>
  </div>

app/views/card_charges/charges_by_month.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">Cargos por Mes y Categoría</h1>
  <div class="text-center mt-4">
    <%= link_to "Página principal", root_path, class: "btn btn-primary" %>
  </div>
  <br> <hr>

  <%= form_with url: charges_by_month_card_charges_path, method: :get, class: "row g-3 mb-4" do |f| %>
    <div class="col-md-6">
      <%= f.label :start_date, "Fecha inicial:", class: "form-label" %>
      <%= f.date_field :start_date, class: "form-control", value: @start_date %> 
    </div>
    <div class="col-md-6">
      <%= f.label :end_date, "Fecha final:", class: "form-label" %>
      <%= f.date_field :end_date, class: "form-control", value: @end_date %> 
    </div>
    <div class="col-md-12 d-flex justify-content-center">
      <%= f.submit "Aplicar filtros", class: "btn btn-primary" %>
    </div>
  <% end %>

  <% if @charges_by_category_and_month.any? %>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Categoría</th>
          <% @charges_by_category_and_month.values.first.keys.each do |month| %>
            <th><%= month.strftime("%B %Y") %></th>
          <% end %>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category&.name || "Sin categoría" %></td>
            <% @charges_by_category_and_month.values.first.keys.each do |month| %>
              <td class="text-end"><%= number_to_currency(@charges_by_category_and_month[category][month] || 0) %></td>
            <% end %>
            <td class="text-end"><strong><%= number_to_currency(@charges_by_category_and_month[category].values.sum) %></strong></td>
          </tr>
        <% end %>
        <tr> 
            <td><strong>Totales mensuales</strong></td>
            <% total_sum = 0 %>
            <% @charges_by_category_and_month.values.first.keys.each do |month| %>
                
              <% month_total = current_user.card_charges.where(
                CardCharge.connection.adapter_name == 'SQLite' ? 
                  "strftime('%Y-%m', date) = ?" : 
                  "to_char(date, 'YYYY-MM') = ?",
                month.strftime("%Y-%m")
              ).sum(:amount) %>
                
                <td class="text-end"><strong><%= number_to_currency(month_total) %></strong></td>
                <% total_sum += month_total %>
            <% end %>
            <td class="text-end"><strong><%= number_to_currency(total_sum) %></strong></td>
        </tr>
      </tbody>
    </table>
  <% else %>
    <p class="mt-4 text-center">No se encontraron cargos para el período seleccionado.</p>
  <% end %>
</div>

app/views/card_charges/home.html.erb
<div class="container mt-5">
  <nav class="navbar navbar-expand-lg navbar-light my-navbar mb-4"> 
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png", height: "30", alt: "Logo" %> <div class="d-inline-block align-middle">CardCharges</div> 
      <% end %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.email %>
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><%= link_to 'Editar perfil', edit_user_registration_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= button_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 mb-4">
      <div class="card shadow">
        <div class="card-body">
          <%= form_with url: card_charges_path, method: :post do |form| %>
            <div class="mb-3">
              <%= form.label :card_type, "Tarjeta", class: "form-label" %>
              <%= select_tag :card_type, options_from_collection_for_select(Card.all, :id, :name, params[:card_type]), prompt: "Seleccione una tarjeta", class: "form-select" %> 
            </div>
            <div class="mb-3">
              <%= form.label :file, "Archivo", class: "form-label" %>
              <%= form.file_field :file, class: "form-control" %>
            </div>
            <%= form.submit 'Procesar archivo', class: "btn btn-primary w-100" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <hr>
  <div class="text-center">
    <%= link_to "Asignar categorias manualmente", assign_categories_card_charges_path, class: "btn btn-primary" %>
    <%= link_to "Asignar categorias automáticamente", categorize_charges_path, class: "btn btn-primary" %> 
    <hr>
    <%= link_to "CRUD categorías", categories_path, class: "btn btn-primary" %> 
    <%= link_to "CRUD proveedores", vendors_path, class: "btn btn-primary" %>
    <%= link_to "CRUD tarjetas", cards_path, class: "btn btn-primary" %>
    <hr>
    <%= link_to "Reporte de cargos detallado", monthly_report_card_charges_path, class: "btn btn-primary" %>
    <%= link_to "Reporte mensual por categoría", charges_by_month_card_charges_path, class: "btn btn-primary" %>
    <hr>
    <% if user_signed_in? %> <div class="text-center mb-4">
      <%= button_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
    <% end %>
  </div>

</div>

app/views/card_charges/index.html.erb
<h1>Cargos a tarjeta</h1>

<div class="container">
  <div class="text-center mx-auto">
    <%= link_to "Página principal", root_path, class: "btn btn-primary me-2" %> 
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Descripción</th>
      <th>Cantidad</th>
      <th>Tarjeta</th>
    </tr>
  </thead>
  <hr>
  <tbody>
    <% @card_charges.each do |charge| %>
      <tr>
        <td><%= charge.date %></td>
        <td><%= charge.description %></td>
        <td><%= number_with_precision(charge.amount, precision: 2, delimiter: ',') %></td> 
        <td><%#= charge.card.description %></td>
      </tr>
    <% end %>
  
    <table class="credit-card-charges-table">
      <thead>
      </thead>
      <tbody>
      </tbody>
      <tfoot>
        <tr class="totals-row">
          <%#td colspan="2"><strong>Total cargos regulares:</strong> <%= number_with_precision(@cr_total, precision: 2, delimiter: ',') %></td>
          <%#td><strong>Total MSI:</strong> <%= number_with_precision(@msi_total, precision: 2, delimiter: ',') %></td>
          <%#td><strong>Total depósitos:</strong> <%= number_with_precision(@d_total, precision: 2, delimiter: ',') %></td>
        </tr>
        <hr>
        <tr class="totals-row">
          <td colspan="2">
            <strong>Total cargos:</strong> <%= @card_charges.count %>
          </td>
          <td>
            <%# strong>A pagar:</strong> <%= number_with_precision(@cr_total + @msi_total, precision: 2, delimiter: ',') %>
          </td>
          <td></td> 
        </tr>
      </tfoot>
    </table>
  </tbody>
</table>

app/views/card_charges/monthly_report.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">Reporte de Cargos</h1>
  <div class="text-center mt-4">
    <%= link_to "Página principal", root_path, class: "btn btn-primary" %>
  </div>
  <br> <hr>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with url: monthly_report_card_charges_path, method: :get, class: "row g-3 mb-4" do |f| %>
        <div class="col-md-6">
          <%= f.label :start_date, "Fecha inicial:", class: "form-label" %>
          <%= f.date_field :start_date, class: "form-control", value: params[:start_date] || Date.today %> 
        </div>
        <div class="col-md-6">
          <%= f.label :end_date, "Fecha final:", class: "form-label" %>
          <%= f.date_field :end_date, class: "form-control", value: params[:end_date] || Date.today %> 
        </div>
        <div class="col-md-6">
          <%= f.label :category_id, "Filtrar por categoría:", class: "form-label" %>
          <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name, params[:category_id]), { include_blank: "Todas las categorías" }, class: "form-select" %>
        </div>
        <div class="col-md-6"> 
          <%= f.label :card_id, "Filtrar por tarjeta:", class: "form-label" %>
          <%= f.collection_select :card_id, Card.all, :id, :name, { include_blank: "Todas las tarjetas" }, class: "form-select" %>
        </div>
        <div class="col-md-6"> </div>
        <div class="col-md-12 d-flex justify-content-center">
          <%= f.submit "Aplicar filtros", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

  <% if params[:start_date].present? && params[:end_date].present? %>
    <% if @card_charges.any? %>
      <h2>Cargos</h2>
  
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Descripción</th>
            <th>Monto</th>
            <th>Categoría</th> 
          </tr>
        </thead>
        <tbody>
          <% @card_charges.each do |charge| %>
            <tr>
              <td><%= charge.date.strftime("%d/%m/%Y") %></td>
              <td><%= charge.description %></td>
              <td class="text-end"><%= number_to_currency(charge.amount) %></td> 
              <td><%= charge.category&.name || "Sin categoría" %></td>
            </tr>
          <% end %>
          <tr>
            <td colspan="2"><strong>Total de cargos</td>
            <td class="text-end"><strong><%= number_to_currency(@card_charges.sum(:amount)) %></strong></td>
            <td></td>
          </tr>
        </tbody>
      </table>
  
      <% if @category_totals.any? %>
        <h3>Totales por Categoría</h3>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Categoría</th>
              <th>Monto total</th>
              <th>Número de transacciones</th>
            </tr>
          </thead>
          <tbody>
            <% @category_totals.each do |category_name, total_amount| %>
              <tr>
                <td><%= category_name %></td>
                <td class="text-end"><%= number_to_currency(total_amount) %></td>
                <td class="text-end"><%= @card_charges.joins(:category).where(categories: { name: category_name }).count %></td> 
              </tr>
            <% end %>
            <tr>
              <td><strong>Total</strong></td>
              <td class="text-end"><strong><%= number_to_currency(@category_totals.values.sum) %></strong></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      <% end %>
  
      <% if @account_totals.any? %>
        <h3>Totales por Cuenta</h3>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Nombre de cuenta</th>
              <th>Monto total</th>
              <th>Número de transacciones</th>
            </tr>
          </thead>
          <tbody>
            <% @account_totals.each do |card_id, total_amount, transaction_count| %>
              <tr>
              <td><%= Card.find(card_id).name %></td>
                <td class="text-end"><%= number_to_currency(total_amount) %></td>
                <td class="text-end"><%= transaction_count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
  
    <% else %>
      <p class="mt-4 text-center">No se encontraron cargos para el período seleccionado.</p>
    <% end %>

  <% else %>
    <p class="mt-4 text-center">No se han aplicado filtros aún.</p>
  <% end %>
</div>